version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: todo_nodejs
    env_file: .env
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_DATABASENAME=$DB_DATABASENAME
    ports: 
      - $APP_PORT:8080
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - db
    command: /home/node/app/node_modules/.bin/nodemon app.js
  db:
    image: mysql
    container_name: todo_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-network
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASENAME}
  adminer:
    image: adminer
    container_name: todo_adminer
    restart: always
    networks:
      - app-network
    ports:
        - $ADMINER_PORT:8080
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:  